### ISSUE TITLE
Переиспользование utschool-js api

### ISSUE THREAD

**Issue by ishmelev23** [u-transnet/utschool-ui#1]
https://github.com/u-transnet/utschool-ui/blob/dev/src/components/api/acceptApplication.js#L16

Во всех файлах components/api при очередном запросе заново инициализируешь api, что влечет за собой повторное подключение к bitshares - что занимает 1-2 секунды.
Просто переиспользуй один и тот же экземпляр api, privateKey можно инициализировать отложено, смотри документацию к проекту.

**Comment by MarkupUa** [comment]
Убрал переиспользование utschool-js api 
https://github.com/u-transnet/utschool-ui/commit/638cab01a2348f29cbd7eba6f83bdc321ba0f383

Спасибо
